// Code generated by github.com/reedom/copygen
// DO NOT EDIT.

// Package copygen contains the setup information for copygen generated code.
package copygen

import (
	"github.com/reedom/copygen/examples/automatch/domain"
	"github.com/reedom/copygen/examples/automatch/models"
)

func _processErr(*domain.Account, *models.Account, *models.User) error {
	return nil
}
func _process(*domain.Account, *models.Account) {
}

// Func1 copies a *models.Account to a *domain.Account.
func Func1(tA *domain.Account, fA *models.Account) {
	_process(tA, fA)
	// *domain.Account fields
	tA.ID = fA.ID
	tA.Name = fA.Name
	tA.Email = fA.Email
	tA.User.Password.Password = fA.Password
}

// Func2 copies a *models.Account, *models.User to a *domain.Account.
func Func2(tA *domain.Account, fA *models.Account, fU *models.User) (err error) {
	err = _processErr(tA, fA, fU)
	if err != nil {
		return
	}
	// *domain.Account fields
	tA.ID = fA.ID
	tA.Name = fA.Name
	tA.Email = fA.Email
	tA.User.UserID = fU.UserID
	tA.User.Username = fU.Username
	tA.User.Password.Password = fA.Password

	return
}

// Func3 copies a *models.Account to a *domain.Account.
func Func3(tA *domain.Account, fA *models.Account) {
	// *domain.Account fields
	tA.ID = fA.ID
	tA.Name = fA.Name
	tA.Email = fA.Email
	tA.User.Password.Password = fA.Password
	_process(tA, fA)
}

// Func4 copies a *models.Account, *models.User to a *domain.Account.
func Func4(tA *domain.Account, fA *models.Account, fU *models.User) (err error) {
	// *domain.Account fields
	tA.ID = fA.ID
	tA.Name = fA.Name
	tA.Email = fA.Email
	tA.User.UserID = fU.UserID
	tA.User.Username = fU.Username
	tA.User.Password.Password = fA.Password
	err = _processErr(tA, fA, fU)

	return
}
