// Code generated by 'yaegi extract github.com/reedom/copygen/cli/models'. DO NOT EDIT.

package extract

import (
	"reflect"
	
	"github.com/reedom/copygen/cli/models"
	"github.com/reedom/copygen/cli/models/debug"

)

func init() {
	Symbols["github.com/reedom/copygen/cli/models/models"] = map[string]reflect.Value{
		// type definitions
		"Field":            reflect.ValueOf((*models.Field)(nil)),
		"FieldOptions":     reflect.ValueOf((*models.FieldOptions)(nil)),
		"Function":         reflect.ValueOf((*models.Function)(nil)),
		"FunctionOptions":  reflect.ValueOf((*models.FunctionOptions)(nil)),
		"Generator":        reflect.ValueOf((*models.Generator)(nil)),
		"GeneratorOptions": reflect.ValueOf((*models.GeneratorOptions)(nil)),
		"Type":             reflect.ValueOf((*models.Type)(nil)),
	}

	Symbols["github.com/reedom/copygen/cli/models/models/debug"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"PrintFieldGraph":     reflect.ValueOf(debug.PrintFieldGraph),
		"PrintFieldRelation":  reflect.ValueOf(debug.PrintFieldRelation),
		"PrintFieldTree":      reflect.ValueOf(debug.PrintFieldTree),
		"PrintFunctionFields": reflect.ValueOf(debug.PrintFunctionFields),
	}
}
