// Code generated by github.com/switchupcb/copygen
// DO NOT EDIT.

// Generator should strip either "//go:build ignore" or "go:build exclude" line.

// Package copygen contains the setup information for copygen generated code.
package copygen

import (
	service "github.com/switchupcb/copygen/examples/main/domain"
	data "github.com/switchupcb/copygen/examples/main/models"
)

// Generator should strip "//go:generate line.

// ModelsToDomain copies a *data.Account to a *service.Account.
func ModelsToDomain(tA *service.Account, fA *data.Account) {
	// *service.Account fields
	tA.ID = fA.ID
	tA.Name = fA.Name
}
